config/routes.rb
Tongo::Application.routes.draw do

  root to: 'static_pages#home'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :tracks do
    member do
      get :download
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :tracks,   only: [:create, :destroy, :show, :edit, :update]
  resources :relationships,  only: [:create, :destroy]
  resources :comments,  only: [:new, :create, :destroy]

  match '/signup',   to: 'users#new'
  match '/signin',   to: 'sessions#new'
  match '/signout',  to: 'sessions#destroy'

  match '/contact',  to: 'static_pages#contact', via: 'get'
  match '/about',    to: 'static_pages#about', via: 'get'
  
 

end

app/models/track.rb
class Track < ActiveRecord::Base
  attr_accessible :title, :track_file, :description
  has_attached_file :track_file,
                    url: ':s3_domain_url',
                    path: "assets/#{Rails.env}/:class/:id/:filename",
                    storage: :s3,
                    s3_credentials: File.join(Rails.root, 'config', 'aws.yml')

  has_many :comments, dependent: :destroy
  belongs_to :user
  default_scope order: 'created_at DESC'
  validates :user_id, presence: true
  validates :description, length: { maximum: 3000 }
  validates_attachment :track_file, presence: true,
    content_type: { content_type: /(video|audio)\/ogg/i }

  def self.from_users_followed_by(user)
    followed_user_ids = "SELECT followed_id FROM relationships
                         WHERE follower_id = :user_id"
    where("user_id IN (#{followed_user_ids}) OR user_id = :user_id",
          user_id: user.id)
  end

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  before_filter :signed_in_user
  before_filter :authorized, only: [:delete, :update]

  def create
    @track = current_user.tracks.build(params[:track])
    if @track.save
      flash[:success] = "Upload Successful!"
      redirect_to root_path
    else
      flash[:error] = "I'm sorry, please upload your track in .ogg format."
      redirect_to root_path
    end
  end

  def show
    @track = Track.find(params[:id])
    @user = User.find(@track.user)
    @comment = current_user.comments.build
  end

  def destroy
   @track = Track.find(params[:id]).delete
   flash[:success] = "'#{@track.title}' has been deleted!"
   redirect_to root_path
  end

  def edit
    @track = Track.find(params[:id])
  end

  def update
    if @track.update_attributes(params[:track])
      flash[:success] = "'#{@track.title}' updated!"
      redirect_to track_path
    else 
      flash[:error] = "Your description can't be longer than 3000 characters"
      render 'edit'
    end
  end

  def download
    @track = Track.find(params[:id])
    data = open(@track.track_file.url)
    send_data data.read, filename: @track.title + ".ogg",
                         type: @track.track_file.content_type,
                         x_sendfile: true
  end

  private

    def authorized
      @track = current_user.tracks.find_by_id(params[:id])
      redirect_to root_path if @track.nil?
    end

end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/tracks/_comment.html.erb
<li class = comment>
  <%= link_to gravatar_for(comment.user, size: 55), user_path(comment.user) %>
  <%= link_to comment.user.name, user_path(comment.user), class: "name" %>
  <span class = "time"><%= time_ago_in_words(comment.created_at) %> ago </span>
  <% if comment.user == current_user %>
    <%= link_to "delete this comment",
                 comment_path(comment.id),
                 class: "delete",
                 method: :delete,
                 data: { confirm: "Are you sure you want to delete this comment? " +
                                  "This action cannot be undone." } %>
  <% end %>
  <p><%= comment.content %></p>
</li>

app/views/tracks/_comments.html.erb
<div class = "comment-wrap">
  <h1>Comments</h1>
  <% unless current_user?(@user) %>
    <%= render 'comments/comment_form'%>
  <% end %>
  <ul class = "comments">
    <% if @track.comments.empty? %>
      <p>No one has commented on this track.</p>
    <% else %>
      <% @track.comments.each do |comment| %>
        <%= render 'comment', comment: comment %>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/tracks/_description.html.erb
<div class = "description-wrap">
  <h1>Track description</h1>
  <p>
  <% if current_user?(@user) && @track.description.blank? %>
    <%= link_to "Add a description for '#{@track.title}'.",
                 edit_track_path %>
  <% elsif !@track.description.nil? %>
    <%= @track.description %>
  <% end %>
  </p>
</div>

app/views/tracks/_track.html.erb
<li class = "track">
  <div class = "play play-pause"></div>
  <div class = "pause play-pause"></div>
    <%= link_to track.title, track_path(track), class: :title %>
    <span class = "created_at">
    submitted 
    <%= time_ago_in_words(track.created_at) %> ago
    <% unless track.user_id == @user.id %>
      by
    <% end %>
  </span>
  <%= link_to 'download', download_track_path(track), class: "options download" %>
  <% if track.user == current_user %>
    <%= link_to "edit", edit_track_path(track), class: "options edit" %>
    <%= link_to "delete", track_path(track),
                 class: "options delete",
                 method: :delete,
                 data: { confirm: "Are you sure you want to delete? " +
                                   "This action cannot be undone." } %>
  <% elsif params[:controller] == 'static_pages' and params[:action] == 'home' %>
    <%= link_to gravatar_for(track.user, size: 18), track.user %>
    <%= link_to track.user.name, track.user, class: "user-name" %>
  <% end %>
  <span class = "timer"></span> 
  <div class = "progress-bar"><span class = "progress"></span></div>
  <audio src= "<%= track.track_file.url %>"></audio>
</li>

app/views/tracks/edit.html.erb
<% provide :title, "Update Track" %>
<div id = "form-wrap">
  <h1>Update <%= @track.title %></h1>
  <%= form_for @track do |f| %>

    <div class="form-element">
      <%= f.label :title  %>
      <%= f.text_field :title  %>
      <span class = "error"></span>
    </div>

    <div class="form-element">
      <%= f.label :description %>
      <%= f.text_area :description %>
      <span class = "error"></span>
    </div>

    <div class="form-element">
      <%= f.submit "Update!", class: "button red" %>
    </div>

  <% end %>
</div>

app/views/tracks/show.html.erb
<% provide(:title, "Track") %>
<%= render 'shared/show_sidebar' %>
<div class = "audio-wrap">
  <%= render 'track', track: @track %>
</div>
<div class = "track-content-wrap">
  <%= render 'description' %>
  <%= render 'comments' %>
</div>