config/routes.rb
Tongo::Application.routes.draw do

  root to: 'static_pages#home'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :tracks do
    member do
      get :download
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :tracks,   only: [:create, :destroy, :show, :edit, :update]
  resources :relationships,  only: [:create, :destroy]
  resources :comments,  only: [:new, :create, :destroy]

  match '/signup',   to: 'users#new'
  match '/signin',   to: 'sessions#new'
  match '/signout',  to: 'sessions#destroy'

  match '/contact',  to: 'static_pages#contact', via: 'get'
  match '/about',    to: 'static_pages#about', via: 'get'
  
 

end

app/views/shared/_dropdown.html.erb
<div class = "dropdown ">
  <%= link_to gravatar_for(current_user, size: 14) + " " + current_user.name,
    "#", class: "dropdown-toggle pull-right green" %>
    <ul class="dropdown">
      <li>
        <%= link_to "profile", current_user, class: "orange" %>
      </li>
      <li>
        <%= link_to "update", edit_user_path(current_user), class: "blue" %>
      </li>
      <li>
        <%= link_to "sign out", signout_path, class: "red" %>
      </li>
    </ul>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id = "form_errors">
    <ul class = "errors">
      <% @user.errors.full_messages.each do |error| %> 
        <li><%= error %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

app/views/shared/_no_tracks.html.erb
<p>
<% if current_user?(@user) %>
  You have not uploaded any tracks.
<% else %>
  <%= @user.name %> has not uploaded any tracks.
<% end %>  
</p>

app/views/shared/_show_flash.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

app/views/shared/_show_sidebar.html.erb
<div class = "sidebar">
  <%= render 'shared/user_info' %>
  <%= render 'shared/stats' %>
  <% if current_user?(@user) && @user.bio.nil? %>
    <%= link_to 'add a bio!', edit_user_path(current_user) %>
  <% else %>
    <%= render 'shared/user_bio' %>
  <% end %>
</div>

app/views/shared/_signin_error.html.erb
<%= "We couldn't find you! Please #{link_to('signup', signup_path)} or try again.".html_safe %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_track_form.html.erb
<h2>Add a track</h2>
<%= form_for @track do |f| %>
  <div class = "form-element">
    <%= f.label :title %>
    <%= f.text_field :title, class: "track" %>
  </div>

  <div class = "form-element">
    <%= f.label :track_file %>
    <%= f.file_field :track_file %>
  </div>
  <%= f.submit "Post", class: "button red" %>
<% end %>

app/views/shared/_user_bio.html.erb
<div class = "bio">
  <p>
    <%= @user.bio %>
  </p>
</div>

app/views/shared/_user_info.html.erb
<h1 class = "pull-left">
  <%= link_to gravatar_for(@user, size: 100), user_path(@user), class: "user" %>
  <div class = "info">
    <h4><%= link_to @user.name, user_path(@user), class: "user" %></h4>
    <% if current_user == @user %>
      <%= link_to "update profile", edit_user_path(@user), class: 'update' %>
    <% end %>
  </div>
</h1>