config/routes.rb
Tongo::Application.routes.draw do

  root to: 'static_pages#home'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :tracks do
    member do
      get :download
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :tracks,   only: [:create, :destroy, :show, :edit, :update]
  resources :relationships,  only: [:create, :destroy]
  resources :comments,  only: [:new, :create, :destroy]

  match '/signup',   to: 'users#new'
  match '/signin',   to: 'sessions#new'
  match '/signout',  to: 'sessions#destroy'

  match '/contact',  to: 'static_pages#contact', via: 'get'
  match '/about',    to: 'static_pages#about', via: 'get'
  
 

end

app/views/layouts/_footer.html.erb
<footer>
  <div class = "footer-content">
    <%= link_to "about", about_path, class: "orange" %>
    <%= link_to "home", root_path, class: "red" %>
    <%= mail_to "wrchapin@gmail.com", "contact", class: "blue" %>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="header-content">
    <%= link_to image_tag("logo.png", alt: "tombo_logo"), root_path, id: "logo" %>
    <nav>
      <ul>
        <li><%= link_to "home", root_path, class: "orange" %>
        </li><li><%= link_to "about", about_path, class: "red" %>
        </li><li><%= link_to("users", users_path, class: "blue") if signed_in? %></li>
      </ul>
    </nav>
    <% if signed_in? %>
      <%= render 'shared/dropdown' %>
    <% else %>
      <%= link_to "sign in", signin_path, class: "green pull-right" %>
    <% end %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset = "utf-8">
    <title><%= full_title yield(:title) %></title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
  <%= render 'layouts/header' %>

  <%= render 'shared/show_flash'%>

  <div id = "main-content">
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>

  <%= debug(params) if Rails.env.development?%>
  </body>
</html>